name: ci

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: ci CamperRank
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: /home/code/Web31-CamperRank/frontend/yarn.lock
      - run: yarn install
      - run: yarn test
