name: ci

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: ci CamperRank
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          script: |
            cd /home/code/Web31-CamperRank/frontend
            yarn install
            yarn test
            cd /home/code/Web31-CamperRank/backend
            npm install
            npm ci
            npm run build --if-present
            # npm test
