name: CI CamperRank Frontend Source Code

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    name: lint backend source code
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: './frontend/**'
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: use cache for dependencies
        id: cached-backend-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

#      - name: Install Dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: |
#          cd frontend
#          yarn install
#
#      - name: lint frontend source code
#        run: |
#          cd frontend
#          yarn run lint

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: lint frontend source code
        run: yarn run lint

  test:
    name: ci frontend source code
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: './frontend/**'
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: use cache for dependencies
        id: cached-frontend-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

#      - name: Install Dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: |
#          cd frontend
#          yarn install
#
#      - name: Run test
#        run: |
#          cd frontend
#          yarn run test

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run test
        run: yarn run test

  build:
    name: ci frontend source code
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: './frontend/**'
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: use cache for dependencies
        id: cached-frontend-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

#      - name: Install Dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: |
#          cd frontend
#          yarn install
#
#      - name: Run test
#        run: |
#          cd frontend
#          yarn build

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run test
        run: yarn build