name: CI CamperRank Frontend Source Code

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: ci frontend source code
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Cache yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')}}
      - run: |
          cd frontend
          yarn install
          yarn test

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"
      #     cache-dependency-path: /frontend/yarn.lock
      # - run: yarn install
      # - run: yarn test
