name: CI CamperRank Frontend Source Code

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  ci:
    name: ci frontend source code
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 16.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')}}
      - run: |
          cd frontend
          yarn install
          yarn test
